all:
	g++ -c -g -o HardwareController.o HardwareController.cpp
	g++ -c -g -o HardwareController_Test.o HardwareController_Test.cpp
	g++ -o executible HardwareController_Test.o HardwareController.o
	rm *.o
